## Reading csv files from multiple random URLs

In [13]:
import pandas as pd

In [14]:
# Prepare the csv links with under e list
http = 'https://'
csv_file_links = [
    'archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
    'raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
    'web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv',
    'archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',
    'archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv',
    'archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'   
]
frames = []
for i, link in enumerate(csv_file_links):
    df = pd.read_csv(http + link, encoding='unicode_escape')
    df.insert(0, 'inserted data data', 'Collected information from website')
    # Append the result in a list
    frames.append(df)

In [16]:
# check the length of the preared array
print(len(frames))
# display all frames data index by index
for i in range(0, len(frames)):
    print(f'frame[{i}]: {frames[i]}' + '\n')

6
frame[0]:                      inserted data data  5.1  3.5  1.4  0.2     Iris-setosa
0    Collected information from website  4.9  3.0  1.4  0.2     Iris-setosa
1    Collected information from website  4.7  3.2  1.3  0.2     Iris-setosa
2    Collected information from website  4.6  3.1  1.5  0.2     Iris-setosa
3    Collected information from website  5.0  3.6  1.4  0.2     Iris-setosa
4    Collected information from website  5.4  3.9  1.7  0.4     Iris-setosa
..                                  ...  ...  ...  ...  ...             ...
144  Collected information from website  6.7  3.0  5.2  2.3  Iris-virginica
145  Collected information from website  6.3  2.5  5.0  1.9  Iris-virginica
146  Collected information from website  6.5  3.0  5.2  2.0  Iris-virginica
147  Collected information from website  6.2  3.4  5.4  2.3  Iris-virginica
148  Collected information from website  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 6 columns]

frame[1]:                      inserted data data     crim    zn  indus  chas    nox  \
0    Collected information from website  0.00632  18.0   2.31     0  0.538
1    Collected information from website  0.02731   0.0   7.07     0  0.469
2    Collected information from website  0.02729   0.0   7.07     0  0.469
3    Collected information from website  0.03237   0.0   2.18     0  0.458
4    Collected information from website  0.06905   0.0   2.18     0  0.458
..                                  ...      ...   ...    ...   ...    ...
501  Collected information from website  0.06263   0.0  11.93     0  0.573
502  Collected information from website  0.04527   0.0  11.93     0  0.573
503  Collected information from website  0.06076   0.0  11.93     0  0.573
504  Collected information from website  0.10959   0.0  11.93     0  0.573
505  Collected information from website  0.04741   0.0  11.93     0  0.573

        rm   age     dis  rad  tax  ptratio       b  lstat  medv
0    6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1    6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2    7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3    6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4    7.147  54.2  6.0622    3  222     18.7  396.90   5.33  36.2
..     ...   ...     ...  ...  ...      ...     ...    ...   ...
501  6.593  69.1  2.4786    1  273     21.0  391.99   9.67  22.4
502  6.120  76.7  2.2875    1  273     21.0  396.90   9.08  20.6
503  6.976  91.0  2.1675    1  273     21.0  396.90   5.64  23.9
504  6.794  89.3  2.3889    1  273     21.0  393.45   6.48  22.0
505  6.030  80.8  2.5050    1  273     21.0  396.90   7.88  11.9

[506 rows x 15 columns]

frame[2]:                      inserted data data  Survived  Pclass  \
0    Collected information from website         0       3
1    Collected information from website         1       1
2    Collected information from website         1       3
3    Collected information from website         1       1
4    Collected information from website         0       3
..                                  ...       ...     ...
882  Collected information from website         0       2
883  Collected information from website         1       1
884  Collected information from website         0       3
885  Collected information from website         1       1
886  Collected information from website         0       3

                                                  Name     Sex   Age  \
0                               Mr. Owen Harris Braund    male  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0
2                                Miss. Laina Heikkinen  female  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0
4                              Mr. William Henry Allen    male  35.0
..                                                 ...     ...   ...
882                               Rev. Juozas Montvila    male  27.0
883                        Miss. Margaret Edith Graham  female  19.0
884                     Miss. Catherine Helen Johnston  female   7.0
885                               Mr. Karl Howell Behr    male  26.0
886                                 Mr. Patrick Dooley    male  32.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0                          1                        0   7.2500
1                          1                        0  71.2833
2                          0                        0   7.9250
3                          1                        0  53.1000
4                          0                        0   8.0500
..                       ...                      ...      ...
882                        0                        0  13.0000
883                        0                        0  30.0000
884                        1                        2  23.4500
885                        0                        0  30.0000
886                        0                        0   7.7500

[887 rows x 9 columns]

frame[3]:                       inserted data data  \
0     Collected information from website
1     Collected information from website
2     Collected information from website
3     Collected information from website
4     Collected information from website
...                                  ...
1594  Collected information from website
1595  Collected information from website
1596  Collected information from website
1597  Collected information from website
1598  Collected information from website

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
...                                                 ...
1594  6.2;0.6;0.08;2;0.09;32;44;0.9949;3.45;0.58;10.5;5
1595  5.9;0.55;0.1;2.2;0.062;39;51;0.99512;3.52;0.76...
1596  6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.7...
1597  5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71...
1598  6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;...

[1599 rows x 2 columns]

frame[4]:                       inserted data data  \
0     Collected information from website
1     Collected information from website
2     Collected information from website
3     Collected information from website
4     Collected information from website
...                                  ...
4893  Collected information from website
4894  Collected information from website
4895  Collected information from website
4896  Collected information from website
4897  Collected information from website

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6
1     6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...
2     8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...
3     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...
4     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...
...                                                 ...
4893  6.2;0.21;0.29;1.6;0.039;24;92;0.99114;3.27;0.5...
4894  6.6;0.32;0.36;8;0.047;57;168;0.9949;3.15;0.46;...
4895  6.5;0.24;0.19;1.2;0.041;30;111;0.99254;2.99;0....
4896  5.5;0.29;0.3;1.1;0.022;20;110;0.98869;3.34;0.3...
4897  6;0.21;0.38;0.8;0.02;22;98;0.98941;3.26;0.32;1...

[4898 rows x 2 columns]

frame[5]:                        inserted data data  39          State-gov   77516  \
0      Collected information from website  50   Self-emp-not-inc   83311
1      Collected information from website  38            Private  215646
2      Collected information from website  53            Private  234721
3      Collected information from website  28            Private  338409
4      Collected information from website  37            Private  284582
...                                   ...  ..                ...     ...
32555  Collected information from website  27            Private  257302
32556  Collected information from website  40            Private  154374
32557  Collected information from website  58            Private  151910
32558  Collected information from website  22            Private  201490
32559  Collected information from website  52       Self-emp-inc  287927

         Bachelors   13        Never-married        Adm-clerical  \
0        Bachelors   13   Married-civ-spouse     Exec-managerial
1          HS-grad    9             Divorced   Handlers-cleaners
2             11th    7   Married-civ-spouse   Handlers-cleaners
3        Bachelors   13   Married-civ-spouse      Prof-specialty
4          Masters   14   Married-civ-spouse     Exec-managerial
...            ...  ...                  ...                 ...
32555   Assoc-acdm   12   Married-civ-spouse        Tech-support
32556      HS-grad    9   Married-civ-spouse   Machine-op-inspct
32557      HS-grad    9              Widowed        Adm-clerical
32558      HS-grad    9        Never-married        Adm-clerical
32559      HS-grad    9   Married-civ-spouse     Exec-managerial

        Not-in-family   White     Male   2174   0   40   United-States   <=50K
0             Husband   White     Male      0   0   13   United-States   <=50K
1       Not-in-family   White     Male      0   0   40   United-States   <=50K
2             Husband   Black     Male      0   0   40   United-States   <=50K
3                Wife   Black   Female      0   0   40            Cuba   <=50K
4                Wife   White   Female      0   0   40   United-States   <=50K
...               ...     ...      ...    ...  ..  ...             ...     ...
32555            Wife   White   Female      0   0   38   United-States   <=50K
32556         Husband   White     Male      0   0   40   United-States    >50K
32557       Unmarried   White   Female      0   0   40   United-States   <=50K
32558       Own-child   White     Male      0   0   20   United-States   <=50K
32559            Wife   White   Female  15024   0   40   United-States    >50K

[32560 rows x 16 columns]